version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080"
    ports:
      - "8080:8080"
    volumes:
      - ./:/code
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    env_file:
      - .env
